const xml=t=>String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const txt=(x,y,t,size=25,color=ink,weight=500,anchor='start')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${color}" font-weight="${weight}" text-anchor="${anchor}">${xml(t)}</text>`;
const lines=(x,y,ls,size=25,color=ink,weight=500,anchor='start')=>ls.map((s,i)=>txt(x,y+i*size*1.35,s,size,color,weight,anchor)).join('');
const circle=(x,y,r,c,opacity=1)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" opacity="${opacity}"/>`;
const rect=(x,y,w,h,c=light,r=10)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${c}"/>`;
const group=(a,s)=>`<g opacity="${a}">${s}</g>`;
const arrow=(x,y,x2,y2,c=gray,t=1,width=3)=>{let xx=x+(x2-x)*clamp(t),yy=y+(y2-y)*clamp(t);return `<path d="M ${x} ${y} L ${xx} ${yy}" stroke="${c}" stroke-width="${width}" fill="none" marker-end="url(#${c===orange?'o':c===blue?'b':'g'})"/>`};
const node=(x,y,w,h,ls,c=ink,size=25)=>rect(x,y,w,h)+lines(x+w/2,y+h/2-(ls.length-1)*size*.67+size*.32,ls,size,c,650,'middle');
function sceneNumber(i){return i===0?1:i;}
const visibleScenes=DATA.map((s,i)=>i).filter(i=>!DATA[i].hidden);
function moveScene(d){const pos=visibleScenes.indexOf(index);select(visibleScenes[Math.max(0,Math.min(visibleScenes.length-1,pos+d))]);}
function frame(k,title,body,foot='Own schematic · Sun et al. (2026)'){return `<svg viewBox="0 0 960 540" role="img" aria-label="${xml(title)}"><style>text{font-family:"Plus Jakarta Sans",Arial,sans-serif}</style><defs>${[['g',gray],['b',blue],['o',orange]].map(([id,c])=>`<marker id="${id}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="${c}"/></marker>`).join('')}</defs><rect width="960" height="540" fill="white"/>${txt(52,43,k,15,blue,600)}${lines(52,91,title.split('|'),31,ink,650)}${body}${txt(52,520,foot,10.5,muted)}${txt(908,520,index<19?`${String(sceneNumber(index)).padStart(2,'0')} / 18`:`B${index-18}`,11,muted,500,'end')}</svg>`}
const charts={12:{title:'Standard LIBERO: a near tie',labels:['OpenVLA-OFT','VLA-JEPA'],values:[97.1,97.2],claim:'+0.1 percentage points',foot:'Paper Table 1 · Success rate (%) · No reported confidence intervals'},13:{title:'LIBERO-Plus: stronger under perturbations',labels:['OpenVLA-OFT','VLA-JEPA'],values:[69.6,79.5],claim:'+9.9 percentage points',foot:'Paper Table 1 · Camera, lighting and layout shifts · Success rate (%)'},14:{title:'Human video improves LIBERO-Plus robustness',labels:['No human video','With human video'],values:[62.9,79.5],claim:'+16.6 percentage points',foot:'Paper Table 2 · Within-method ablation · Success rate (%)'},15:{title:'Human video does not improve every task',labels:['No human video','With human video'],values:[78.4,65.2],claim:'−13.2 percentage points · SimplerEnv Google',foot:'Paper Table 2 · Within-method ablation · Success rate (%)'}};
function smol(){let b=node(52,202,251,92,['Qwen3-VL-2B','Original backbone'],ink,24)+arrow(311,248,360,248,blue)+node(370,202,250,92,['SmolVLM','Adapted backbone'],blue,25)+group(phase(.3,.6),lines(661,217,['>60% lower','backbone memory'],26,blue,650));b+=group(phase(.6,.85),lines(52,378,['Keep the V-JEPA encoder and flow-matching action head.','Cross-attention fusion retains pretrained feature alignment.'],24,ink,500));return frame('Backup B1 · Our preliminary experiments','SmolVLM architectural adaptation',b,'Presenters’ preliminary adaptation · Backbone memory finding, not an end-to-end benchmark claim')}
function dream(){let b=node(52,202,252,87,['Search','Layers + tokens'],ink,25)+arrow(313,245,361,245,blue)+node(370,202,251,87,['Select','Latency + success'],blue,25)+arrow(630,245,676,245,blue)+node(685,202,222,87,['Candidate n0008'],blue,23);b+=group(phase(.4,.7),txt(52,392,'14.2% inference speedup',39,blue,650))+group(phase(.7,.95),txt(52,455,'Stable policy retention in the preliminary candidate result',23,muted));return frame('Backup B2 · Our preliminary experiments','Dream-RSI: self-improving search',b,'Presenters’ preliminary overnight LIBERO harness · Pruned attention candidate')}
function overview(){let b=node(52,173,224,68,['Observation + instruction'],ink,21)+arrow(284,207,314,207,blue)+node(325,173,236,68,['VLM → latent tokens'],blue,23)+arrow(569,207,604,207,blue)+node(615,173,289,68,['Flow-matching action head'],blue,21);b+=node(52,325,224,68,['Encoded state history'],ink,22)+arrow(284,359,314,359)+node(325,325,236,68,['World-model predictor'],ink,22)+arrow(569,359,604,359,orange)+node(615,325,289,68,['Future-target alignment'],orange,23)+arrow(443,249,443,314,blue);b+=txt(52,477,'Video supervises prediction. Robot demonstrations also supervise actions.',22,blue,600);return frame('Backup B3 · Architecture overview','The whole method, after the components are familiar',b,'Own redraw of paper Figure 1 · Original paper available in Sources')}

function buildSVG(){let html='';if(index===19)html=smol();else if(index===20)html=dream();else if(index===21)html=overview();else if(index===22)html=`<div class="math-sheet"><p style="color:${blue}">Backup · Flow matching</p><h1>The equations behind the visual training pair</h1><h2>Mix noise and a demonstrated action chunk</h2><img src="assets/equation-1.png" alt="a tau equals one minus tau times epsilon plus tau times demonstrated action"><h2>Regress the velocity onto the pair’s displacement</h2><img src="assets/equation-2.png" alt="Expected squared error between predicted velocity and demonstration minus noise"><p>Mixing time describes generation progress, rather than physical robot time.</p></div>`;else html='';return html;}
