/* Deterministic authoring export, only enabled on the companion local server. */
const exportButton=document.createElement('button');exportButton.textContent='Export revised presentation';exportButton.id='export-scenes';document.getElementById('notes').append(exportButton);
exportButton.onclick=async()=>{exportButton.disabled=true;presenter.cancel();presenter.manual=false;animation=false;audio.pause();humanClip.pause();robotClip.pause();const out=document.createElement('canvas');out.width=1920;out.height=1080;const c=out.getContext('2d');await document.fonts.ready;sketch.pixelDensity(1);sketch.resizeCanvas(1920,1080);const post=async(name,blob)=>{const r=await fetch('/export/'+name,{method:'POST',body:blob});if(!r.ok)throw new Error('Local export failed '+r.status)};const take=()=>{sketch.redraw();c.drawImage(sketch.canvas,0,0,1920,1080);};
const seek=async t=>{comparisonExportTime=t;await Promise.all([humanClip,robotClip].map(async v=>{const target=Math.min(t,Math.max(0,v.duration-.04));if(Math.abs(v.currentTime-target)<.001&&v.readyState>=2)return;await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Video seek timeout')),10000);v.addEventListener('seeked',()=>{clearTimeout(timeout);resolve()},{once:true});v.currentTime=target;});}));};
const requested=new URLSearchParams(location.search).get('chapters')?.split(',').map(Number);const exportScenes=requested?.length?visibleScenes.filter(i=>requested.includes(sceneNumber(i))):visibleScenes;try{for(const i of exportScenes){index=i;p=1;motion.from=null;motion.exportTime=null;if(i===2||i===0)await seek(8);take();await post(`slide-${String(i+1).padStart(2,'0')}.png`,await new Promise(r=>out.toBlob(r,'image/png')));
if(i<19){for(const val of [.15,.4,.75]){p=val;if(i===2||i===0)await seek(val*motionLength(i));take();await post(`audit-${String(i+1).padStart(2,'0')}-${Math.round(val*100)}.png`,await new Promise(r=>out.toBlob(r,'image/png')));}
const typeSamples={0:[.85,1.05,1.52],3:[9.1,9.24,9.4,16.16],4:[.72,.92],5:[7.15],6:[10.15],7:[.34],9:[20.1,20.24,20.4,34.24],10:[9.87,10,10.16],11:[24.12,24.25,24.4],12:[1.16],13:[1.16],14:[1.16],15:[1.16],18:[.12,.3]};for(const sec of typeSamples[i]||[]){motion.exportTime=sec*1000;p=clamp(sec/motionLength(i));if(i===0)await seek(sec);take();await post(`type-${String(i+1).padStart(2,'0')}-${Math.round(sec*100)}.png`,await new Promise(r=>out.toBlob(r,'image/png')));}motion.exportTime=null;if(new URLSearchParams(location.search).has('typeaudit'))continue;
let chunks=[],error;const enc=new VideoEncoder({output:chunk=>{const b=new Uint8Array(chunk.byteLength);chunk.copyTo(b);chunks.push(b);},error:e=>error=e});enc.configure({codec:'avc1.640028',width:1920,height:1080,bitrate:7000000,framerate:60,avc:{format:'annexb'},hardwareAcceleration:'prefer-hardware'});const n=Math.round(DATA[i].budget*60);motion.dataFrom=charts[i]&&charts[i-1]?charts[i-1].values:null;motion.from=i>=5&&i<=8?poseFor(i-1):null;for(let f=0;f<n;f++){if(i===2||i===0)await seek(f/60);motion.exportTime=f/60*1000;p=Math.min(1,f/60/motionLength(i));take();const frame=new VideoFrame(out,{timestamp:Math.round(f/60*1e6),duration:16667});enc.encode(frame,{keyFrame:f%120===0});frame.close();if(enc.encodeQueueSize>12)await new Promise(r=>setTimeout(r,0));if(f%120===0){exportButton.textContent=`Exporting chapter ${sceneNumber(i)} · ${Math.round(f/n*100)}%`;await new Promise(r=>setTimeout(r,0));}if(error)throw error;}await enc.flush();enc.close();await post(`video-${String(i+1).padStart(2,'0')}.h264`,new Blob(chunks,{type:'video/h264'}));motion.from=null;motion.exportTime=null;}
}exportButton.textContent='Presentation export complete';}catch(e){exportButton.textContent='Export failed: '+e.message;console.error(e);}finally{comparisonExportTime=null;select(4);animation=false;p=1;render();exportButton.disabled=false;sketch.resizeCanvas(innerWidth,innerHeight);}};
