const parser=new DOMParser();let sketch,canvasCtx,framesSeen=0,measureStart=0,frameTimes=[],lastPaint=0;
function num(n,k,d=0){return Number(n.getAttribute(k)||d)}
function paintSVG(svg,c){const doc=parser.parseFromString(svg,'image/svg+xml');if(doc.querySelector('parsererror'))return;function walk(n){let name=n.tagName;if(!name)return;c.save();let opacity=n.getAttribute('opacity');if(opacity!==null)c.globalAlpha*=Number(opacity);let fill=n.getAttribute('fill'),stroke=n.getAttribute('stroke');if(fill&&fill!=='none')c.fillStyle=fill;if(stroke&&stroke!=='none')c.strokeStyle=stroke;if(n.hasAttribute('stroke-width'))c.lineWidth=num(n,'stroke-width');c.lineCap='round';c.lineJoin='round';let path=null;
if(name==='rect'){path=new Path2D();path.roundRect(num(n,'x'),num(n,'y'),num(n,'width'),num(n,'height'),num(n,'rx'))}else if(name==='circle'){path=new Path2D();path.arc(num(n,'cx'),num(n,'cy'),num(n,'r'),0,Math.PI*2)}else if(name==='path'){try{path=new Path2D(n.getAttribute('d'))}catch(e){}}
if(path){if(fill!=='none'&&(fill||!stroke))c.fill(path);if(stroke&&stroke!=='none'){c.setLineDash((n.getAttribute('stroke-dasharray')||'').split(/[ ,]+/).filter(Boolean).map(Number));c.stroke(path)}let marker=n.getAttribute('marker-end');if(marker){let d=n.getAttribute('d'),vals=d.match(/-?\d*\.?\d+/g)?.map(Number)||[];let end=vals.slice(-2),prev=vals.slice(-4,-2);if(vals.length===3&&/H/.test(d)){prev=vals.slice(0,2);end=[vals[2],vals[1]]}else if(vals.length===3&&/V/.test(d)){prev=vals.slice(0,2);end=[vals[0],vals[2]]}if(end.length===2&&prev.length===2){let a=Math.atan2(end[1]-prev[1],end[0]-prev[0]);c.translate(end[0],end[1]);c.rotate(a);c.fillStyle=stroke||blue;c.beginPath();c.moveTo(0,0);c.lineTo(-9,-4);c.lineTo(-9,4);c.closePath();c.fill()}}}
if(name==='text'){c.font=`${Math.round(Number(n.getAttribute('font-weight')||500)/100)*100} ${num(n,'font-size',23)}px "Plus Jakarta Sans",Arial,sans-serif`;c.fillStyle=fill||ink;c.textAlign=({'middle':'center','end':'right'})[n.getAttribute('text-anchor')]||'left';c.fillText(n.textContent,num(n,'x'),num(n,'y'))}
if(!['defs','style','marker','text'].includes(name))for(const child of n.children)walk(child);c.restore()};walk(doc.documentElement)}
function label(c,t,x,y,size=24,color=ink,bold=false,align='left'){c.fillStyle=color;c.font=`${bold?700:500} ${size}px "Plus Jakarta Sans",Arial,sans-serif`;c.textAlign=align;c.fillText(t,x,y)}
function dotC(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
function arrowTip(c,x,y,angle,color,width=2){const length=7+width,half=2.5+width*.4;c.save();c.translate(x,y);c.rotate(angle);c.fillStyle=color;c.beginPath();c.moveTo(0,0);c.lineTo(-length,-half);c.lineTo(-length,half);c.closePath();c.fill();c.restore();}
function segment(c,x,y,x2,y2,color,width=2,head=false){c.save();c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.beginPath();c.moveTo(x,y);c.lineTo(x2,y2);c.stroke();if(head)arrowTip(c,x2,y2,Math.atan2(y2-y,x2-x),color,width);c.restore();}
function kineticLine(c,text,x,y,size,color,bold,t=1,oldText=''){c.save();c.beginPath();c.rect(x-3,y-size-6,905-x,size+14);c.clip();const write=(line,offset)=>{let xx=x;c.font=`${bold?700:500} ${size}px "Plus Jakarta Sans"`;line.split(' ').forEach((word,j)=>{const local=smoothOut((t-j*.015)/.7);label(c,word,xx,y+offset(local),size,color,bold);xx+=c.measureText(word+' ').width;});};if(t<1&&oldText)write(oldText,u=>-u*(size+15));write(text,u=>(1-u)*(size+15));c.restore();}
function headerC(c,k,title,foot){const t=clamp(sceneSeconds()/.38);label(c,k,52,43,15,blue,true);kineticLine(c,title,52,94,31,ink,true,t,motion.oldHeader||'');motion.header=title;label(c,foot,52,520,10.5,muted);label(c,`${String(sceneNumber(index)).padStart(2,'0')} / 18`,908,520,11,muted,false,'right');}
const humanExamples=[1,2,5].map(i=>{const im=new Image();im.src=['assets/human-example-001.png','assets/human-example-002.png','assets/human-example-005.png'][[1,2,5].indexOf(i)];return im});


function bez(t,pts){const u=1-t;return [u*u*u*pts[0][0]+3*u*u*t*pts[1][0]+3*u*t*t*pts[2][0]+t*t*t*pts[3][0],u*u*u*pts[0][1]+3*u*u*t*pts[1][1]+3*u*t*t*pts[2][1]+t*t*t*pts[3][1]]}
function curve(c,pts,color,width=2,end=1,head=false){if(end<=0)return;c.save();c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.lineJoin='round';c.beginPath();for(let i=0;i<=80;i++){const pt=bez(i/80*end,pts);if(!i)c.moveTo(...pt);else c.lineTo(...pt);}c.stroke();if(head){const tip=bez(end,pts),tail=bez(Math.max(0,end-.005),pts);arrowTip(c,...tip,Math.atan2(tip[1]-tail[1],tip[0]-tail[0]),color,width);}c.restore();}
