function render(){if(index===22){let old=stage.querySelector('.math-sheet');if(!old){stage.insertAdjacentHTML('beforeend',buildSVG())}}else{stage.querySelector('.math-sheet')?.remove()}document.getElementById('scrub').value=Math.round(p*1000);document.getElementById('status').textContent=`${DATA[index].speaker} · ${index<19?'Chapter '+sceneNumber(index):'Appendix'}`;if(window.updateTimeline)window.updateTimeline();}
const robotClip=document.createElement('video');robotClip.id='robot-dataset-clip';robotClip.src='assets/droid-demonstration.mp4';robotClip.muted=true;robotClip.loop=false;robotClip.playsInline=true;robotClip.preload='auto';robotClip.setAttribute('aria-hidden','true');robotClip.style.display='none';document.body.append(robotClip);const robotPoster=new Image();robotPoster.src='assets/droid-demonstration-poster.jpg';
const humanClip=document.createElement('video');humanClip.id='human-dataset-clip';humanClip.src='assets/human-demonstration.mp4';humanClip.muted=true;humanClip.playsInline=true;humanClip.preload='auto';humanClip.style.display='none';humanClip.setAttribute('aria-hidden','true');document.body.append(humanClip);let comparisonStart=0,comparisonHold=null,comparisonExportTime=null;function comparisonTime(){return comparisonExportTime??(presenter.manual?sceneSeconds():comparisonHold??Math.max(0,(performance.now()-comparisonStart)/1000));}function startComparison(){comparisonStart=performance.now();comparisonHold=null;for(const v of [humanClip,robotClip]){v.currentTime=0;v.play().catch(()=>{});}}function holdComparison(t){comparisonHold=t;for(const v of [humanClip,robotClip]){v.pause();if(Number.isFinite(v.duration))v.currentTime=Math.min(t,Math.max(0,v.duration-.04));}}
function select(n){beginTransform(n);humanClip.pause();robotClip.pause();audio.pause();playing=false;animation=false;index=Math.max(0,Math.min(DATA.length-1,n));p=0;auto=false;animation=false;document.querySelector('main').scrollTop=0;audio.src=index<19?`assets/narration-${String(index+1).padStart(2,'0')}.mp3?v=story-20261002-v4`:'';document.querySelectorAll('nav .slide-link').forEach(b=>b.classList.toggle('active',Number(b.dataset.scene)===index));document.getElementById('noteTitle').textContent=(DATA[index].backup?'Backup':'Slide '+sceneNumber(index))+' · '+DATA[index].speaker;document.getElementById('script').textContent=DATA[index].notes;document.getElementById('delivery').textContent=(DATA[index].deliveryCues||[]).map(c=>Math.floor(c.time/60)+':'+String(Math.floor(c.time%60)).padStart(2,'0')+' — '+c.instruction).join('\n');document.getElementById('source').textContent=DATA[index].source+'\nReference: https://arxiv.org/abs/2602.10098v1';document.getElementById('caption').textContent=index<19?'Right / Space: next animation · Left: previous animation · Chapters: jump to a section':'Optional backup — outside the narrated main talk';document.getElementById('talk').textContent='Play narration';document.getElementById('animate').textContent='Pause motion';if(index===2||index===0)startComparison();resetPresenter();render();}
DATA.forEach((s,i)=>{if(s.hidden)return;let b=document.createElement('button');b.className='slide-link';b.dataset.scene=String(i);b.innerHTML=`<small>${i<19?String(sceneNumber(i)).padStart(2,'0'):'B'+(i-18)} · ${s.speaker}</small><br>${s.title}`;b.onclick=()=>{select(i);document.getElementById('slides').classList.remove('open')};document.getElementById('slides').append(b)});
document.getElementById('prev').onclick=()=>advanceBeat(-1);document.getElementById('next').onclick=()=>advanceBeat(1);document.getElementById('step').onclick=()=>{animation=false;p=Math.min(1,p+.25);render()};document.getElementById('audit').onclick=()=>{animation=false;p=1;if(index===2||index===0)holdComparison(8);render()};document.getElementById('scrub').oninput=e=>{animation=false;p=+e.target.value/1000;if(index===2)holdComparison(p*8);render()};document.getElementById('menu').onclick=()=>document.getElementById('slides').classList.toggle('open');document.getElementById('closeNav').onclick=()=>document.getElementById('slides').classList.remove('open');document.getElementById('notesBtn').onclick=()=>{let n=document.getElementById('notes');n.hidden=!n.hidden};document.getElementById('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>{document.getElementById('welcome').textContent='Use your browser’s full-screen shortcut (Control–Command–F on Mac).';document.getElementById('welcome').style.opacity=1;setTimeout(()=>document.getElementById('welcome').style.opacity=0,5000)});document.getElementById('animate').onclick=()=>{if(p>=1)p=0;animation=!animation;if(index===2||index===0){if(animation)startComparison();else holdComparison(comparisonTime());}last=performance.now();document.getElementById('animate').textContent=animation?'Pause motion':'Animate'};document.getElementById('talk').onclick=async()=>{if(index>=19)return;if(playing){audio.pause();return}if(audio.ended)audio.currentTime=0;auto=true;try{await audio.play()}catch(e){document.getElementById('caption').textContent='Narration is being prepared. You can explore every animation now.'}};
audio.onplay=()=>{playing=true;document.getElementById('talk').textContent='Pause narration'};audio.onpause=()=>{playing=false;document.getElementById('talk').textContent='Play narration'};audio.onended=()=>{render();};audio.ontimeupdate=()=>{};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='ArrowRight'){e.preventDefault();advanceBeat(1)}else if(e.code==='ArrowLeft'){e.preventDefault();advanceBeat(-1)}else if(e.code==='Space'){e.preventDefault();advanceBeat(1)}else if(e.key==='n'){document.getElementById('notesBtn').click()}else if(e.key==='Escape'){document.getElementById('slides').classList.remove('open');document.getElementById('notes').hidden=true}else if(e.key==='f'){document.getElementById('fullscreen').click()}});
let uiTimer;function revealUI(){document.getElementById('controls').classList.add('show');document.getElementById('menu').classList.add('show');clearTimeout(uiTimer);uiTimer=setTimeout(()=>{document.getElementById('controls').classList.remove('show');document.getElementById('menu').classList.remove('show')},2200)}document.addEventListener('pointermove',e=>{if(e.clientY>innerHeight-85||e.clientX<45)revealUI()});revealUI();setTimeout(()=>document.getElementById('welcome').style.opacity=0,5000);
select(0);
window.deck={select,render,setProgress(v){p=clamp(v);render()},get index(){return index},get progress(){return p},data:DATA};
// One retained canvas. Motion uses a monotonic time clock, independent of narration events.

stage.addEventListener('click',()=>advanceBeat(1));stage.addEventListener('contextmenu',e=>{e.preventDefault();advanceBeat(-1)});
